### ISSUE TITLE
Missile definitions

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#1]
Let's get a basic set of missile definitions into the addon.
*There's already a few examples in lua\acf\shared\missiles\missile_aam.lua - are these ok for a first showing?
*Keeping in mind that once we release a missile type, we can't easily remove it again for fear of backwards incompatibility.

**Comment by Cre8or** [comment]
I'll be redoing the missile definitions properly once the framework around them - including modifiers for penetration, ROF and the like - is fully implemented. Mostly porting real life stats over while keeping balance in check.

**Comment by Bubbus** [comment]
I added the XCF pods in 13d043570c7551618419c5ee6c3b09c166b0f29d, gave them a quick pass but they're still not really balanced.
Also added 'reloadmul' for the rack defs, should help with reload times.

**Comment by ColBeckett** [comment]
i found nice reference about ATGMs we can make:
http://www.alternatewars.com/BBOW/Weapons/Russian_ATGMs.htm
its only russian one but you can see its penetration , guidance type and year of production

**Comment by Bubbus** [comment]
Hey, how are we doing for SAMs?  Once we have one of those then what's left?  To make a quick balance-pass on what weapons we have and then... ?

Meanwhile I'm passing the time by making post-beta things :S 102970a45cec84f6bd16d2946c1a544a62e8102a

**Comment by Cre8or** [comment]
Sorry for the lack of activity - I've got ASMs balanced out, still waiting for the Stinger (which iirc is our only SAM) and I'll get on with the AAMs (AMRAAM and AIM-9).

**Comment by ColBeckett** [comment]
stinger is ready :v i made model yesterday
only racks todo

about other sams - we can make that massive ones like sa-2 or mim-23 and make it slower than other missiles but it will have like 3x more fuel

**Comment by Cre8or** [comment]
Just finished defining FFARs properly. They can take more HE filler, penetrate a lot more than they used to (30-40mm), and have a higher ROF. You have no idea how much fun I'm having with this right now.

**Comment by Cre8or** [comment]
AAMs are now defined, everything else in here seems to be done too. Reopen if I forgot anything.
