### ISSUE TITLE
Rocket pods

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#11]
Add a type of rack that disables missile explosions unless its armour is pierced.
Use the same entity as racks, just stuff some more logic in there.
Armour should be defined accurately in a config file to allow easy balance.
Loadable missiles should be limited solely and precisely by caliber.
Fire-rates should be faster than rack missiles.
Firepower should be lower than rack missiles.
Should be able to hide the missile (to save fps + obscure unfolded fins etc)

Any launcher that is tube-shaped or cartridge-like is a pod.  Racks differ in zero protection + variable caliber mounting.

**Comment by Cre8or** [comment]
Will we have support for tube/round-based missiles on racks? I'm thinking it'd be cool to at least allow for 2x racks for the BGMs, to reduce the amount of physical entities attached to contraptions. However, this would conflict with your idea.
Alternatively, I could make a rack model that comes with 2 BGM tubes permanently mounted on it. Any thoughts on this?

http://www.operatorchan.org/w/src/140012690464.jpg

**Comment by Bubbus** [comment]
We can:
- Make 1xTOW, 2xTOW... models and classify these as new pods.  (more models needed, no code needed - already supported.)
- Spawn a tube model and parent it to the missile (doubled entity count, susceptible to deletion etc, code needed, less models needed.)
- Set the missile's model to the tube model until it's fired (code needed, less models needed, tube will "disappear" when fired.)
  - We can add more code here to drop a tube model from the rack on the clientside, but this is more code + complication + definitely feature-creep.

If we go for an option that needs more code, I'd only do that as a post-beta feature.

**Comment by Cre8or** [comment]
I'll just go for the double-BGM model in that case, since the tubes will always be mounted on the racks, no matter what.

**Comment by Bubbus** [comment]
Done in 7569dc7b5bbdf203874c589875caf1d047b961b1
