### ISSUE TITLE
Missile bodygroups

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#13]
Add a system that applies different missile bodygroups in different situations.  Ideally:

flight bodygroup:
racked: all fins folded etc (on the rack)
flying: all fins unfolded etc (during flight)

warhead bodygroup (stretch goal):
he, heat... if applicable for visual identification of warhead (ex. rpg rounds)

This lets us change the missile based on its situation, which is nice for tube rockets and guided bombs.  Not a big priority because it's purely cosmetic, but would be really nice.

**Comment by ColBeckett** [comment]
it can be done - simply modify base prop and "cut" elements that should be unfolded/folded and save it as bodygroup

also warhead bodygroup can works like my muzzles bodygroups in acf

**Comment by ColBeckett** [comment]
hmm how about to make changed textures (skin) instead of bodygroups ( i speak about that warhead bodygroup) - so lets say HEAT missile will be pure yellow with red tip, HE all white with black tip etc

**Comment by ColBeckett** [comment]
about bodygroups - i thinking to make something similar to RPG ammo:
http://i.imgur.com/REtnYfm.jpg

**Comment by ColBeckett** [comment]
About hellfire - i think to make bodygroup too depent on guidance type:
IR bodygroup should looks like this:
https://c2.staticflickr.com/4/3625/3446475333_eebf15f89b.jpg
and radio bodygroup should looks like this:
http://www.cat-uxo.com/communities/0/004/010/791/960/images/4616270702.jpg
let me know is this possible to code that missile

**Comment by Bubbus** [comment]
Yes it's possible to apply the bodygroups based on any of the missile's attributes.

**Comment by Bubbus** [comment]
Added in fc7351c596bdc259c0d28b1bc041723baf37fe5c.
