### ISSUE TITLE
Bomb definitions

### ISSUE THREAD

**Issue by ColBeckett** [Bubbus/ACF-Missiles#14]
Here i leave you my bomb list. Ofc Im going to make models of them
Each bomb will get 2 bodygroups (only the last one will get 3)

50kg (FAB50 and AN-M30)
100kg (FAB100 and AN-M57)
250kg (FAB250 and AN-M64)
500kg (FAB500 and AN-M65)
1000kg (AN-M66) - there is no FAB bomb with that diameter propably will use one of bomb i put down there
2000kg (FAB2000, AN-M56 and HC-lb (Blockbuster Bomb))

feel free to add other types like GBU (guided) or CBU (cluster)

bombs should be balanced - as you know 1000kg doesnt mean that it have 1000kg of TNT - most of the time Its warhead makes up 50% of the total weight so 1000kg will have 500kg of TNT

http://www.leteckemotory.cz/vyzbroj/fab/fab_nakres.gif

several pics of FAB bombs - i will use FAB1500 as 1000kg bomb i dont see the point adding FAB3000 and FAB5000 (ammocrate is too small and we dont want bombs of mass destruction in acf)

**Comment by ColBeckett** [comment]
i think to make 6x50kg or 6x100kg rack instead of 4x50kg (that one we use now is mostly made for rockets/missiles - bombs cant be set as in that rack)
https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT5j_gEviP8BPBbPJXaFuNMFC8MVvV4B2g6xYW2f7Nc4UwrXZQYPQ

**Comment by Cre8or** [comment]
How are the bombs coming along? From what I've read, only a rack model's left to do. Is everything else ready?

**Comment by ColBeckett** [comment]
as for beta everything is done - maybe some small changes in APHE penetration 

my idea is to make 100kg APHE with half HE filler penetration buff to 35mm - but i have to test more bombs vs more tanks. gona try to use them like in wiki (50kg vs 5t, 100kg vs 15t etc.)
bombs are really heavy now and my 10t bomber can carry only one 500kg bomb 

for now i abandon 6x rack and 2000kg bombs
1000kg bomb will be done in post-beta if I decide to make one cause i have ideas about guide bombs and maybe even cluster bombs if its possible todo

for now we can close that and reopen if needed
