### ISSUE TITLE
Missile characteristics from bulletdata + definition

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#15]
ent_cre_missile looks like this:
![ent_cre_missile.ConfigureFlight](https://dl.dropboxusercontent.com/u/902553/ShareX/2015-01/2015-01-28_22-50-02.png)

Things like self.MotorLength etc should hopefully be influenced by the data in self.BulletData before beta.

**Comment by Cre8or** [comment]
Missiles now inherit values from BulletData:
https://github.com/Bubbus/ACF-Missiles/commit/c70d5be21dc2adc9fca1b0fb445d464075c12a5f
