### ISSUE TITLE
Rocket pod definitions

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#18]
Need a few rocket pods defined before release.  We can import the XCF FFARs and use the new TOW.

Fire-rates should be faster than rack missiles.
Firepower should be lower than rack missiles.
Should be able to hide the missile (to save fps + obscure unfolded fins etc)

Any launcher that is tube-shaped or cartridge-like is a pod. Racks differ in zero protection + variable caliber mounting.

**Comment by ColBeckett** [comment]
how big rocket pods should be
i know 7 pod is ok but how about some big ones like
http://upload.wikimedia.org/wikipedia/commons/7/78/A-4_Skyhawk_rocket_pod.JPG
also i think we should add some bodygroups to them

**Comment by Bubbus** [comment]
Pods can apply caliber restrictions now in c140fea5ef1b37bb94e27cf5a222caea1353ac0d, let me know in a new issue if we need anything else.

**Comment by Cre8or** [comment]
Say, now that we have different rack sizes for some missiles (1x, 2x and 4x for BGM-71Es, 2x and 4x for AGM-114s), can we add a way of selecting a specific rack? Or do we already have that feature?

**Comment by Bubbus** [comment]
Not yet, but now that I know how to add things to the acf menu I can add something like that...  lemme see.

**Comment by Bubbus** [comment]
Done the rack selection in 1af96f9bfa2ef38bb126a7ef942788fa0bbe728d

**Comment by Cre8or** [comment]
Since most pods are already defined by now, and since news ones can be added within a matter of minutes, I think we can close this.
