### ISSUE TITLE
Missile parenting

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#2]
When the missiles are parented to the rack, if the rack is moving then they can be parented in odd positions.  Parenting needs to be the same regardless of situation.

**Comment by Cre8or** [comment]
This could be why racks don't work on my end, as the missiles are removed when unparenting due to their origin being too far away.

**Comment by Bubbus** [comment]
Seems fixed after testing, remake/reopen this issue if it re-appears.

**Comment by Bubbus** [comment]
Not actually fixed!  It's all to do with the order of parenting and positioning.  Maybe looking into how holos do it might help.

**Comment by Bubbus** [comment]
Maybe fixed again in fa09aab92ef0827e9720ea900d58bbbb09f59844...
please???
