### ISSUE TITLE
Dupe deny error

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#20]
[ERROR] addons/acf-missiles-master/lua/autorun/server/duplicatordeny.lua:19: attempt to index field 'WhiteList' (a nil value)
1. Deny - addons/acf-missiles-master/lua/autorun/server/duplicatordeny.lua:19
   1. unknown - addons/acf-missiles-master/lua/autorun/server/sv_acf_missiles.lua:298

Timer Failed! [Simple][@addons/acf-missiles-master/lua/autorun/server/sv_acf_missiles.lua (line 298)]

?!?!?!

**Comment by Cre8or** [comment]
Could be linked to yesterday's GMod update. People have reported that it broke every tool they have, Cre8ive is also affected by this. If you haven't modified anything related to the tools, then this is probably the cause.

**Comment by ColBeckett** [comment]
another error i get after update it

[ERROR] addons/acf-missiles/lua/entities/acf_rack/init.lua:711: Couldn't find the 1x BGM-71E gun-definition!
1. error - [C]:-1
   1. MakeACF_Rack - addons/acf-missiles/lua/entities/acf_rack/init.lua:711
   2. unknown - addons/acf-missiles/lua/entities/acf_missile_to_rack/init.lua:39

**Comment by Bubbus** [comment]
Fixed Beckett's tow error in a2c436e168899c38ea7775f579dc4960f25093e6
Please make a new issue for every error because pressing the big "Close and comment" button feels awesome.

**Comment by Bubbus** [comment]
OK I don't know how this even happened to you, but here's a quick-fix: ce3734c1d86ded60cb2458812cfdccf6cbe61d46
Re-open if this persists.
