### ISSUE TITLE
HEAT penetration issue

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#21]
HEAT is piercing below its supposed capability, probably due to the initial pierce caused by missile detonation.  Fix by restoring heat penetrator velocity after detonation.

**Comment by Cre8or** [comment]
Just for the record, restoring the velocity may not be good enough; a multiplier (ontop of the restored velocity perhaps) would give us more control about penetration in regard of certain missile types.

**Comment by ColBeckett** [comment]
also - i think we should add APHE to bombs - to make some kind of anti-ship bombs

after testing i get maximum 5mm penetration :V so any ideas how incrase that?

**Comment by Bubbus** [comment]
Fiiiiixed in 9ec326d2135773738339d93b2096bbab7d1b930d

**Comment by Cre8or** [comment]
Bump, I still need a penetration velocity multiplier variable for the ammo definitions, so that ASMs can actually do anything against armour (besides blowing everything except the armour itself off). Resetting the velocity upon impact isn't enough to deal proper damage.

**Comment by Bubbus** [comment]
I got u m8 d4e34f47481570f8c6b45329c8de06b5a0020e73

**Comment by ColBeckett** [comment]
heat/APHE penetration still doesnt works - so i reopen this issue

**Comment by Bubbus** [comment]
HEAT seems to work just fine.  Make a new issue if there's still interest in an APHE multiplier; it's simply not implemented at all just now.  It's a post-beta goal now.
