### ISSUE TITLE
Confusing caliber messages

### ISSUE THREAD

**Issue by ColBeckett** [Bubbus/ACF-Missiles#22]
After I try to link ammo for cannons (so wrong ammo) i have message "Only 30mm rounds can fit in this gun"
if i try to link 30mm ammo to rack i get "2xRK racks cannot be loaded by 30mmHMG ammo!" (seems that one works)

**Comment by Bubbus** [comment]
This isn't really a bug, it's caused by the new changes in here: c140fea5ef1b37bb94e27cf5a222caea1353ac0d

I should work on the messages because I can see how they can be confusing.

**Comment by Bubbus** [comment]
Maybe 57adc6f3f4e4a4b57344a14abeb471003cc875f0 will help.  If things are still unclear then re-open this issue and tell me what the problem is.
