### ISSUE TITLE
Add XCF Pod definitions.

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#23]
Need to add the XCF models to this mod and then enable the XCF pod defs and missile defs.
After this the missiles probably need to be balanced, but they should already be in a good place coming from XCF.

**Comment by ColBeckett** [comment]
about xcf pods models - there are in good quality and there is no point to make new models
only bigger ones like 24 rocket pod or some kind of bodygroups

**Comment by Bubbus** [comment]
We need to be careful with the high-capacity pods and racks: each missile is another entity and could cause lag.  I don't think it'll be that bad because people drive 300-prop cars around all the time, but we should know if having that many entities will cause a problem before we commit time to making models etc.

**Comment by ColBeckett** [comment]
seems legit
we should stay with this till beta release then

**Comment by Cre8or** [comment]
Could we perhaps set some launchers to behave more like guns in that regard? I'm thinking flare pods won't need to have any models spawned in them, as they can easily carry up to 20-30 flares per unit. We'll need a different system for them.

**Comment by ColBeckett** [comment]
or just use acf gun system and make it like smoke launcher

**Comment by Cre8or** [comment]
Thing is, flare pods should work without ammo crates, much like the FFAR pods do. With the difference being that it doesn't spawn any flare entities until they're required (when firing). I'm not sure how difficult this would be to implement, as I can't think of any ACF gun that has this behaviour (more than 1 round loaded inside the gun).

**Comment by Bubbus** [comment]
Autocannons, HMGs etc have magazines, I'm hoping we can make an "autocannon flare launcher" and then somehow trick it into launching flare effects instead of bullet effects.

**Comment by Bubbus** [comment]
61364ba5154e8c508f9bca7737d42a49c706d221 + 13d043570c7551618419c5ee6c3b09c166b0f29d.

I'm going to move the flare discussion to the flare issue.
