### ISSUE TITLE
Beta Models definition

### ISSUE THREAD

**Issue by ColBeckett** [Bubbus/ACF-Missiles#24]
for now we need some models to replace old ACF/XCF ones before we release Beta:
list:
1xRack:
- Bomb based rack (BRU-11A)
- FIM-92 Stinger rack 1x - done

2xRack
- Hellfire rack  - done
- BGM-71 rack - Done
- Bomb based rack - (BRU-33A)
- FIM-92 Stinger rack 2x - done

3xRack 
- 50kg, 100kg and 250kg bomb based rack (BRU-42) - Done

4xRack
- Hellfire rack - done
- BGM-71 rack - Done
- FIM-92 Stinger rack 4x

missiles:
Hellfire Missile - done
Stinger Missile - done

**Comment by Cre8or** [comment]
I'm still working on a 2x and 4x BGM-71E rack, the 1x rack being the round tube itself.

These racks are specific though, and can't be used with any other missiles (or bombs for that matter).

**Comment by ColBeckett** [comment]
today i will make that first rack bru-47
so i guess we gona need some AA-based racks aswell?

**Comment by Cre8or** [comment]
To my knowledge we've got the following racks/pods planned or already implemented:

Weapon specific:
- BGM-71E racks (1x - 2x - 4x)
- AGM-114 Hellfire racks (2x - 4x)
- FIM-92 Stinger racks (1x - 2x - 4x)

Non-specific:
- ACF/XCF missile racks (1x - 2x - 4x)
- bomb racks (1x - 2x - 3x)

If anything's wrong with that list, let me know.

**Comment by ColBeckett** [comment]
i agree with that
in () i set model i will base on

**Comment by Cre8or** [comment]
How far's your AGM-114 rack? And would it be easy to make a 4x version of it aswell?

For reference, I'm thinking of something along the lines of this:
http://images.military.com/media/equipment/ordnance/agm-114-hellfire/agm-114-hellfire-001.jpg

With my BGM-71E rack, making a 4x version out of the existing 2x rack is as easy as copy-pasting another copy and adding two extra attachment pins to secure them in place.

**Comment by ColBeckett** [comment]
i think it will be easy aswell - copy paste with some small changes

**Comment by ColBeckett** [comment]
2xHellfire rack - done
4xHellfire rack - done
Hellfire missile - done

4xBGM-71 rack - Done
50kg and 100kg bomb based rack (BRU-42) - Done

**Comment by ColBeckett** [comment]
about stinger rack - you think about "tube based" like in avenger?:
http://upload.wikimedia.org/wikipedia/commons/c/c9/Avenger_missile.jpg

**Comment by Cre8or** [comment]
Yes, however that's the far stretch goal as this is a very specific rack for just one vehicle. What's more important is the single missile tube model and eventually a 2x rack for it that can be mounted on helicopters: http://i3.photobucket.com/albums/y66/magioverlord21/FULL-STI4.jpg

**Comment by ColBeckett** [comment]
ok
maybe you have some nice stinger missile references - its really hard to find any good blueprints of it

**Comment by Cre8or** [comment]
There's quite a few decent pictures in this post:

http://sassik.livejournal.com/70937.html

**Comment by ColBeckett** [comment]
thats more than enough - thanks a lot

**Comment by ColBeckett** [comment]
Stinger Missile - done

**Comment by Bubbus** [comment]
We have a ton of missiles now so I'm going to close this.  Make a new issue to discuss post-beta missiles.
