### ISSUE TITLE
Refill crate reload speeds

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#26]
During regular use, racks should have _awful_ reload speeds to balance their huge firepower advantages vs guns.  The idea is that if refill crates speed up the reload rate then we can take the liberty of making in-field reload rates even more awful.  It'd also encourage aircraft to land to re-arm.  Yes/no?

If we go for this, let's squeeze it in after the beta.  Plenty of feature creep already!

**Comment by Cre8or** [comment]
Personally I'm a big fan of having to bring ACF vehicles back to a supply point to rearm, and I do just that whenever I fly my jet.
Plus, If we're still going for the idea of rocket pods/racks being reloadable from ammo crates, then I think it's a good idea to make that process slow for balancing purposes. Refill crates would become an excellent alternative for rearming, so hopefully people will use them more.

**Comment by Bubbus** [comment]
Added in 102970a45cec84f6bd16d2946c1a544a62e8102a, re-open for comments/suggestions.
