### ISSUE TITLE
ACFMenu options disappearing.

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#3]
The guidance and fuse options disappear if ammo type is changed

**Comment by Cre8or** [comment]
On this topic, would it be possible or the fuse and guidance selections to always pick the first option in the list when the menu is loaded? (rather than having to select one the first time)

**Comment by Bubbus** [comment]
sure #8

**Comment by Bubbus** [comment]
yee a8b5a095b5389d593575ded1d6d53f8d00a70d2a
