### ISSUE TITLE
Missile effect without propellant

### ISSUE THREAD

**Issue by Cre8or** [Bubbus/ACF-Missiles#31]
Apparently firing BGMs with 0.01 propellant (lowest possible slider value) causes the missile to have the usual smoke trail, as if actually in flight. Figured I might aswell throw it out here, as it might just be a small bug that can easily be fixed.

**Comment by Bubbus** [comment]
And there was me thinking I'd fixed that.  I think I know what it is, will fix.

**Comment by Bubbus** [comment]
Hi, see if 6748fcd86fc92651282d5fab95e4f3f62b2b5ae5 fixes this.

**Comment by Bubbus** [comment]
Confirmed fixed
