### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#34]
We've got entity missiles.  Someone might want to de-parent the missile.  Someone might teleport it somewhere and then trigger the detonation.  Someone might parent the missile to something else.  ACF is competitive => people are dicks.  Be the fun police.

Not too important during beta, but should be tightened up over time.

**Comment by Cre8or** [comment]
Surely we could just make the missiles nonSolid to prevent the biggest chunk of problems that originate from people wiring/unparenting the missiles directly from the rack. As for messing with individual missiles using E2, this was already possible with FFARs, but nobody ever used it for anything.

**Comment by Bubbus** [comment]
Well really even after all this, anyone can setPos the rack and then fire the missile.  I'd rather they did that.  Added some safeguards in a34e80767047483adb71c1ed6d64ee9527dc49a2.
