### ISSUE TITLE
APHE ammo for bombs

### ISSUE THREAD

**Issue by ColBeckett** [Bubbus/ACF-Missiles#35]
We have to add some kind of APHE penetration multipler (similar to HEAT in missiles) for bombs.
That multipler should include filler value and HE value and then generate penetration cause now every bomb has 0mm penetration in APHE

we can think about this after beta

**Comment by ColBeckett** [comment]
if thats easy to implement we can do that before beta

**Comment by Bubbus** [comment]
I can do this if we're waiting on other things before we release the first beta.  AFAIK we have stinger racks and initial quick-pass of balance to do, anything else, anyone?

**Comment by ColBeckett** [comment]
today i gona make that stinger x1 rack
model is somehow done, texture halfway (global illumination ready so only details todo)

there are other issues so if other ones are done or registered as post-beta - we can take care on this one

**Comment by Cre8or** [comment]
I need to balance out the AAMs some more today, aswell as the FFARs as those are a lot more powerful now than they used to be.
I'm going to need some help with guidances and fuses, especially with radar. I've been thinking that it should allow for an entity input, to simplify target reacquisition during flight, and to let players handle the locking on. Any ideas on how feasible this would be?

**Comment by ColBeckett** [comment]
I think we have to test them and then decide... its hard to say now how fast/  slow that should happend

about ballancing stuff:
first idea is to make some test server for max 4 people and test that missiles on it - everything from bombs HE fillers to Guidance system
i have pretty good internet connection so i will be able to make that server (i hope)

another and i think better idea is to put that in cre8ve - annouce acf-missile pre beta test and change map for 1 day to gm_butties and test that missiles all day - we can also make topic on glutt forum and ppl will post impressions - its some kind of pre-beta test of that

i would like to make that beta testing this sunday - next week i will be totaly not available

**Comment by Cre8or** [comment]
Sunday may work for me so long as it's before 4-5 PM. Also, we already intend on testing the missiles on our server, so that shouldn't be an issue.

**Comment by Bubbus** [comment]
I'm going to be drunk this weekend - if you need anything then create issues for them before tomorrow night and I'll handle it after work!

**Comment by Cre8or** [comment]
Not sure if I asked you this before, but could you look into the missile racks' undo queuing at some point? It's nothing major but it screws with my test rig every now and then.

**Comment by Bubbus** [comment]
Oh yeah, will do.  #38

**Comment by Bubbus** [comment]
Added baba15133eacb8ee78b941da7f931b65afdd9912, which shows penetration values for APHE at 50m/s, 100 and 200.  You'll get 50m/s from a long fall or a divebomb, or a direct drop from a fast plane into the side of a wall.

If you still need the APHE multiplier after this, let me know.  The values seem pretty sane to me so far.

**Comment by ColBeckett** [comment]
we can press that magic close button for now:)

**Comment by ColBeckett** [comment]
We can now Press that magic close button:)
