### ISSUE TITLE
Rack entity input

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#36]
Give racks an entity input for guidance systems to use.  Should be fine - Radar can just fly straight if it's outside the cone, and wire already has ent-tracking via an e2 proxy.  
Once this happens, wire will be technically superior to radar due to no tracking-loss.  It'll be up to us to ensure radar-equipped missiles always have an agility edge over wire missiles.

**Comment by Cre8or** [comment]
I tweaked the way agility works, it now does what it says on the tin. ASMs are generally very unmaneuvrable, meaning only small target leading adjustements will be possible during operation. SAMs and AAMs on the other hand will have much higher agility, for as long as their motor lasts.

**Comment by Bubbus** [comment]
Boss.

**Comment by Bubbus** [comment]
05ff0b766090fc6a0a182b19142d11317d9d0c11 boop
