### ISSUE TITLE
Ammo blacklist

### ISSUE THREAD

**Issue by Cre8or** [Bubbus/ACF-Missiles#39]
The way it works right now is that when you select a round type, then the round class, you may not combine the two to create illogical stuff like smoke AGM-114s.

However, if you select the round class first, say the AGM-114, and then select smoke, you bypass the blacklist altogether.

I'm not sure if this is just on my end, or whether it's restricted to the AGM-114s, but this definitely needs investigating.

**Comment by Bubbus** [comment]
my GOD wrong ISSUE

Fixt 2ac554f52cc548949d3dc6142090014fd5dd516f

(i goofed up with the link-time checking on the racks, but funnily enough this is a common bug with acf-tool:)
![lel](https://dl.dropboxusercontent.com/u/902553/ShareX/2015-03/2015-03-01_21-26-15.png)
