### ISSUE TITLE
Missiles + entity driving

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#4]
Missiles which are parented to the rack can be moved around with the entity drive feature.  Need to make sure they can't be moved at all.

**Comment by Cre8or** [comment]
Missiles on racks seem to be non solid on the server (physgun beam goes through) but not on the client (smartsnap grid shows). Perhaps add a clientside hack to make it non-solid there aswell, or use the CanDrive hook: http://wiki.garrysmod.com/page/SANDBOX/CanDrive

**Comment by Bubbus** [comment]
Check out 00cf9c36 + b7d7d7c6
