### ISSUE TITLE
missiles little more user friendly

### ISSUE THREAD

**Issue by ColBeckett** [Bubbus/ACF-Missiles#44]
I spoke with our testers - waxx and ferv and they said that missile guide system is a bit too complicated:

17:59 - [FALOTI] Waxx: ferv and i liked what we saw but their use is a little complex
18:00 - [FALOTI] Waxx: that the means of arming and linking them should be simplified
18:11 - [FALOTI] Waxx: basically it just needs to be a little more user friendly

what you think? how we can make it even more frindly?

**Comment by Bubbus** [comment]
I think it's about as user friendly as the rest of ACF lol, we're just so used to the stuff we already deal with...
That said, if I know what parts of the arming/linking process are too complicated, then I'll know what to focus on simplifying?

BTW is GMod fixed yet?  I'm not going to touch any code until I can know what broken things are actually my fault.

**Comment by ColBeckett** [comment]
waxx said that it is, ferv said the same in acf general thread on facepunch
also seems server dont crashing that many times as before
