### ISSUE TITLE
Missile range?

### ISSUE THREAD

**Issue by Dale1994** [Bubbus/ACF-Missiles#46]
I seems when missiles run out of propellant they don't even try maneuvering even though they still have velocity. They also just drop like rocks.

**Comment by Dale1994** [comment]
Yes, it seems after their HEAT nerf their range is VERY bad.

**Comment by Dale1994** [comment]
Yes it seems the range on the StA missiles are vastly lower since the StA pen nerf.

**Comment by Cre8or** [comment]
Could you give us a more specific example of when/how this occurs? I'll need at least a bit of information to work with, like your ammo crate settings, the guidance you were using, and which missile is affected by this.

**Comment by Dale1994** [comment]
Why yes, I have max propellant that the missile can contain. It's propellant last less than a second and after that it just flies in the direction of when it last had propellant. I can see the missile point where I am telling it to go but it just flies in the same direction once the propellant runs out. The drop seems to have been user error and is no longer an issue. To sum it up, I would like to see the missiles fly towards its target destination even if it's out of propellant, instead of a straight line.

**Comment by Bubbus** [comment]
Closing old balance issues due to subsequent changes.  Re-open if you feel the issue persists.
