### ISSUE TITLE
FFAR rack mass

### ISSUE THREAD

**Issue by Mecaguy03** [Bubbus/ACF-Missiles#54]
Several missile racks are not the masses they say they should be. The 40mm and 70mm FFAR racks weigh 200kg and 400kg respectively when spawned, when the description says 6 and 12kg.

The description for the stinger also says it is 101kg, which is incorrect.

**Comment by Cre8or** [comment]
Where did you get the 6kg and 12kg from? Are those the masses of the FFAR pods when spawned as props? Also, were the racks loaded at all?

I believe these values are part of a balancing measure we were doing, similar to how some ACF guns have masses far beyond realism. I'll take a look at our rack definitions and see if anything needs changing.

**Comment by ColBeckett** [comment]
there is small issue with props aswell - acf ents cant weight less than props
most of racks has been fixed in this case

**Comment by Mecaguy03** [comment]
The 6 and 12kg are in the description of the racks. Unloaded they were 200 or 400kg, and as props the 40mm and 70mm are 85kg.

When loaded they were over those masses, and as far as balancing goes, 200kg for the smallest rack seems like a lot.

If the weights are staying as they are, the descriptions should be updated to show the real weights.

**Comment by Cre8or** [comment]
I see the issue now: the displayed weight is that of the missile itself, not of the rack. I don't remember the reason behind this, but it does seem like a good idea to have it display the rack's weight instead (unless it's an inherited function from ACF, in which case this would become far more difficult to achieve).

**Comment by Bubbus** [comment]
Oh snap, thanks for the report.  Will check it when I get the chance.

**Comment by Cre8or** [comment]
In the meantime, I lowered the mass on the 70mm and 40mm FFAR pods to a significantly lower amount, which I think is fair considering they missiles are unguided.

https://github.com/Bubbus/ACF-Missiles/commit/0bef7af768fa63126c2d664549095d0abfe03534

**Comment by Bubbus** [comment]
Sure, gotta always keep in mind though that these pods are effectively high
caliber HMGs with incredible HEAT performance and small mags, but the
recent rack buff has also given them really nice reload times too.  Got to
balance them with guns as well as other missiles!
