### ISSUE TITLE
Arming delay slider

### ISSUE THREAD

**Issue by Cre8or** [Bubbus/ACF-Missiles#55]
It appears that the missile's arming delay slider doesn't always initialise when spawning an ammo crate. This causes the missiles to have no arming delay at all.

Here's how to reproduce the issue:
- click on an ammo type from the ACF menu (HE, HEAT, smoke)
- if your round type is one of the custom missile/bomb types, scroll down to the arming delay slider. Otherwise, select a missile type first (AGM, BGM, FFAR, bombs, etc...), then proceed to scroll down.
- the slider should look like this:

![](https://dl.dropboxusercontent.com/u/7087057/i/slider.png)

A temporary in-game fix is to select an item from either use the fuse package or round type selections. It seems like this will reload the ACF menu's page, and will fix the arming delay slider. It is also possible to pick the item from the drop-down lists that is already currently selected.

Whatever it is that the drop-down lists do, it fixes the slider. So maybe we could take whichever method they're using and implement it in the ACF menu, so that whenever it is opened/loaded the slider is initialised properly.

**Comment by Bubbus** [comment]
> This causes the missiles to have no arming delay at all.

It does?  I'll need to check that as I'm sure I made it check for a minimum.  If it doesn't then this is a pretty big bug...

I did everything I could find to make the slider appear properly when it loads.  It still doesn't appear properly when it loads.  I'm basically 'hacking into' the tool at this point to make it show anything at all - I'd love to make it work but it might be more effort than it's worth.

**Comment by Cre8or** [comment]
I remember testing this with 2 ammo crates, one spawned with the slider bugged and one after I manually fixed it (and set it to the minimum delay). Using the first crate, I could fire missiles into the ground at point blank range and they'd instantly blow up, while with the latter one, they would bounce off as expected. This is the only reason that I'm mentionning this at all, because it renders the dudding system pretty much useless at the moment.

**Comment by Cre8or** [comment]
Turns out the ACF missile's init.lua is using the wrong variable at line 428. It is using:
`Round.armdelay`
whereas it should be using:
`GunData.armdelay`

This will make it use the minimum arming delays that were set in the missile definitions. However, it will also bypass the delay that was set with the slider altogether, meaning the delay can not currently be changed. Should be a simple fix.

**Comment by Bubbus** [comment]
Finally fixed the data issue with 0153025e9bd893632f30b448158b78d1e3c205fa
The graphical issue remains, but can be fixed by toggling the package types.

**Comment by Cre8or** [comment]
Closing as the bug is no longer affecting gameplay. The UI bug remains but can be fixed by cycling guidance packages once (back and forth).
