### ISSUE TITLE
9K121 Vikhr

### ISSUE THREAD

**Issue by Mecaguy03** [Bubbus/ACF-Missiles#58]
Would be really awesome as a new ATGM, especially for aircraft.

**Comment by ColBeckett** [comment]
model can be done asap
problem start when you have to ballance it - we need correct data sheet - that one on wiki i think isnt much
EDIT: actually i found one so now everything depend what cre8or say
http://www.repulestudomany.hu/folyoirat/2014_3/2014-3-03-0178_Szilvassy_Laszlo.pdf

**Comment by Mecaguy03** [comment]
Awesome, if you make different rack types for it, you should make racks of two, six, and eight. Those are the standard configs you can find on vehicles, although if you dont want to make that many I think just a 2 and a 6 rack would do.

**Comment by ColBeckett** [comment]
i dont say that i will make that :v: 
there are other stuff more important than new missile type atm

**Comment by ColBeckett** [comment]
Dont know why you close this thread - it may be postponned cus we have more important stuff todo

and i plan to add more soviet/russian rockets like AT-3

**Comment by ColBeckett** [comment]
added ataka instead of this
