### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by Mecaguy03** [Bubbus/ACF-Missiles#59]
You really should specify units for the arming delay and distance sliders. Is the arming delay in seconds, miliseconds, is the distance in meters, inches, what?

**Comment by Cre8or** [comment]
The arming delay is in seconds, the distance is in inches.

We will add the respective units to the sliders soon.

**Comment by Cre8or** [comment]
[Done!](https://github.com/Bubbus/ACF-Missiles/commit/deb4574491b1354f593866c97eecf67975692660)
