### ISSUE TITLE
Wirelink error

### ISSUE THREAD

**Issue by Stooberton** [Bubbus/ACF-Missiles#63]
Need to add 'if not inp then return nil end' after line 335 of acf_rack/init.lua to keep it from shitting itself if you try to use wirelinks on a rack.

**Comment by Kardel420** [comment]
Tried it out, yes it does cause this error, would be really cool you fix it since he already gave you the solution to the problem, b0ss pls I want my wirelinked racks.

**Comment by Cre8or** [comment]
[Done!](https://github.com/Bubbus/ACF-Missiles/commit/409494238367cafa291c304f0a074dfea147beaf)

Thanks for the report, let me know if the problem persists.
