### ISSUE TITLE
Bullet trace think ahead?

### ISSUE THREAD

**Issue by ALMS999** [Bubbus/ACF-Missiles#66]
17:55 - ALMS: hello
17:56 - Bubbus: hi
17:56 - ALMS: is it intentional that missiles hit the craft when moving?
17:57 - Bubbus: nope
17:56 - ALMS: / would it be possible to add craft veloctiy to the rockets so they don't hit the craft fireing
17:56 - ALMS: ?
17:57 - Bubbus: i'd recommend not mounting them too close to props
17:57 - ALMS: yeah
17:57 - Bubbus: yeah, put it on the github issues page so i don't forget we had this convo lol
17:57 - ALMS: ok
17:57 - ALMS: it would be pod/rack velocity added to the muzzle velocity?
17:59 - Bubbus: tbh, i thought we'd added that already
17:59 - ALMS: hm
17:59 - ALMS: yeah
17:59 - ALMS: wouldn't make sense if you hadn't
17:59 - Bubbus: might be down to the props moving before the missiles get to run their movement traces
17:59 - ALMS: ah
17:59 - ALMS: hm
17:59 - Bubbus: if that's the case, i've got no damn idea how to fix that
17:59 - ALMS: well
17:59 - ALMS: you could add a delay
18:00 - Bubbus: we don't get a pre-physics hook, just a think hook
17:59 - ALMS: ah
18:00 - ALMS: well
18:00 - ALMS: hm
18:00 - ALMS: you're the boss at this
18:00 - ALMS: so
18:00 - ALMS: yeah
18:01 - Bubbus: could make them pretend they're living one tick into the future
18:00 - ALMS: it's in there
18:01 - Bubbus: but goddamn, that sounds like effort
18:00 - ALMS: yeah
18:01 - ALMS: would it be?
18:01 - Bubbus: don't know if it would actually be effort, but it does sound like it
18:01 - ALMS: hm
18:01 - Bubbus: i'd have to see
18:01 - ALMS: would it be something like moving the trace
18:01 - ALMS: depending on the velocity
18:01 - ALMS: then fireing
18:02 - ALMS: when that pos is obtained?
18:02 - Bubbus: it'd be giving the missile one tick of movement for free and then going on from there as normal
18:02 - ALMS: ah
18:02 - ALMS: so it ignores everything within the first tick?
18:02 - ALMS: oh nvm
18:02 - ALMS: don't explain it
18:03 - ALMS: wouldn't make a difference to me
18:03 - ALMS: as long as it works, lol.
18:03 - Bubbus: hah
18:03 - Bubbus: fair enough
18:03 - ALMS: so
18:04 - ALMS: what would I write on the page?
18:04 - ALMS: or
18:04 - Bubbus: just out of interest, put a mortar in the same place as the rack
18:04 - ALMS: yeah
18:04 - ALMS: will do
18:04 - Bubbus: literally so the muzzle is where the rack mount point is
18:05 - Bubbus: if the mortar works fine, i can look at copying the acf bullet logic verbatim
18:04 - ALMS: ye
18:05 - ALMS: don't think it will though
18:06 - Bubbus: ah right
18:06 - Bubbus: yeah just paste the convo in
18:06 - Bubbus: it'll scare the piss out of future me
18:06 - ALMS: lol

**Comment by Bubbus** [comment]
Band-aided with 58c4f3a1aa89af21e60810ed0b22514957ac1f0c.  If anyone has brighter ideas I'm open to them!
