### ISSUE TITLE
4x Strela-1 loaded missle mis-placement

### ISSUE THREAD

**Issue by JakeyCakey** [Bubbus/ACF-Missiles#77]
On the right side of the 4x Strela-1 Missle boxes, the missles are mis-placed compared to the left side.

![images akamai steamusercontent com](https://cloud.githubusercontent.com/assets/7584200/12012612/5ecab3b4-acfd-11e5-8f21-bcb335a39077.jpg)
![4000_screenshots_2015-12-28_00002](https://cloud.githubusercontent.com/assets/7584200/12012620/bd706ac6-acfd-11e5-8d4a-136ae599bfe1.jpg)

**Comment by ColBeckett** [comment]
fixed in 1a966b431c9fa72d16a7fe16b1667f63d4e0942e
