### ISSUE TITLE
Seeking code non-functional (RADAR tracking, RADIO DETONATION)

### ISSUE THREAD

**Issue by ForanIdah** [Bubbus/ACF-Missiles#82]
The latest gmod update has rendered built in acf seeking/tracking broken. Not sure what the cause is.
Tested in SP, and on the FRS and GGG servers

**Comment by Cre8or** [comment]
Unable to reproduce the issue on the latest version, neither in multiplayer nor in singleplayer. If this issue persists, I will need more information to work with (version number, console errors, etc).
