### ISSUE TITLE
ACF-Missiles relies on the BeamNetVars library but doesn't include it

### ISSUE THREAD

**Issue by AbigailBuccaneer** [Bubbus/ACF-Missiles#92]
ACF-Missiles [uses the `ent:{Get,Set}Beam*` functions](https://github.com/Bubbus/ACF-Missiles/blob/0848bf63fc28c0feefa0d1bb22c4a514d515233d/lua/entities/acf_rack/shared.lua#L20) that are implemented by the [BeamNetVars library](https://github.com/wiremod/wire/blob/4acbfe2d95b9b9f27d83be26091c3136136f639d/lua/wire/beam_netvars.lua#L197). It's currently shipped with Wiremod, but we're intending to remove it (wiremod/wire#969, wiremod/wire#1270). It automatically detects when multiple addons ship it and uses the newest one, so the correct thing to do is to include the file with ACF-Missiles.

**Comment by Bubbus** [comment]
Thanks kindly for the warning!  I assume a7971a66 will cover this?

**Comment by AbigailBuccaneer** [comment]
It should! Thanks :ok_hand:
