### ISSUE TITLE
sound error (custom sound not playing)

### ISSUE THREAD

**Issue by DankKKKush** [Bubbus/ACF-Missiles#94]
*** Invalid sample rate (48000) for sound 'acf_extra\airfx\s_hindloop.wav'.
sound "hindloop" produces that error when attempting to be played.

**Comment by Bubbus** [comment]
This isn't related to ACF Missiles, the people at the main ACF repo should be able to help!

https://github.com/nrlulz/acf

**Comment by DankKKKush** [comment]
thanks!
